spring:
  datasource:
    url: jdbc:mysql://localhost:3306/oa?serverTimezone=GMT%2B8&useSSl=false&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
logging:
  level:
    cn.lcl.mapper: trace
  pattern:
#    console: '%p%m%n'
file:
  # 服务器地址
  filePath: C:\\Users\\zy\\Desktop\\lqy
  # 前端地址
  urlPath: C:\\Users\\zy\\Desktop\\lqy
url: http://localhost:8000/#/
wx:
  secret: a2cad0b0e025348fc32202c2cd5798e1