spring:
  datasource:
    url: jdbc:mysql://localhost:3306/oa?serverTimezone=GMT%2B8&useSSl=false&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
logging:
  level:
    cn.lcl.mapper: trace
  pattern:
#    console: '%p%m%n'
file:
  # 服务器地址
  filePath: C:\\Users\\zy\\Desktop\\lqy
  # 前端地址
  urlPath: C:\\Users\\zy\\Desktop\\lqy
url: http://localhost:8000/#/
wx:
  secret: a2cad0b0e025348fc32202c2cd5798e1


  #邮件发送配置
  mail:
    default-encoding: UTF-8
    host: smtp.qq.com
    username: 1519804390@qq.com
    password: nhrbbedpbmqzifeg
    #配置邮箱465端口，否则本地测试可以，放到服务器上就不行
    #这个端口有时候会出错，添加以下ssl配置。或者把端口改为 25
    spring.mail.properties.mail.smtp.ssl.enable: true

    properties.mail.smtp.port: 465
    properties.mail.smtp.auth: true
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true